import type { ForkModel } from "./model";
import { isTool } from "./model";
import type { Call, StepReport } from "../types/gate";

/**
 * "What would change in the contract if this run's behaviour were accepted as the new baseline" -- built
 * purely from the comparison result already fetched (model.run.result.steps), no new backend endpoint.
 * Only MISSING_STEP and UNRECORDED/UNSOURCED_ARGUMENT map cleanly onto a single requires/permits line
 * entering or leaving; ORDER_VIOLATION and FORBIDDEN are shown for context but marked non-acceptable here
 * (see each branch's note) since neither reduces to one line -- order lives at tool-name granularity
 * across the WHOLE contract, and forbids is a deliberate human rule, not something a recording implies.
 */

export type DiffKind = "enter" | "leave" | "info";

export interface ContractDiffEntry {
  id: string;
  kind: DiffKind;
  target: "requires" | "permits" | "order" | "forbids";
  line: string;
  note: string;
  step: StepReport;
}

/** Matches agent_replay/callsig.py's render_call() exactly: tool(arg=value, arg2=value2). */
export function renderCall(call: Call): string {
  if (!isTool(call)) return "";
  const parts = Object.entries(call.args).map(([k, v]) => `${k}=${v}`);
  return `${call.tool}(${parts.join(", ")})`;
}

export function buildContractDiff(model: ForkModel): ContractDiffEntry[] {
  const entries: ContractDiffEntry[] = [];
  for (const row of model.run.result.steps) {
    if (!row.cause) continue;
    if (row.cause === "MISSING_STEP" && row.golden) {
      entries.push({
        id: `leave-${row.step}`,
        kind: "leave",
        target: "requires",
        line: renderCall(row.golden),
        note: "Every reference recording always made this call. This run didn't.",
        step: row,
      });
    } else if ((row.cause === "UNRECORDED" || row.cause === "UNSOURCED_ARGUMENT") && row.candidate) {
      entries.push({
        id: `enter-${row.step}`,
        kind: "enter",
        target: "permits",
        line: renderCall(row.candidate),
        note:
          row.cause === "UNSOURCED_ARGUMENT"
            ? "This argument traces to nothing the model was shown or told -- possibly fabricated. Review carefully before accepting."
            : "Not observed in any reference recording so far.",
        step: row,
      });
    } else if (row.cause === "ORDER_VIOLATION") {
      const call = row.candidate ?? row.golden;
      entries.push({
        id: `info-${row.step}`,
        kind: "info",
        target: "order",
        line: call ? renderCall(call) : "",
        note: "An order rule spans the whole contract, not one call -- edit `order:` in the contract file by hand to change it.",
        step: row,
      });
    } else if (row.cause === "FORBIDDEN") {
      const call = row.candidate ?? row.golden;
      entries.push({
        id: `info-${row.step}`,
        kind: "info",
        target: "forbids",
        line: call ? renderCall(call) : "",
        note: "A forbids rule is a deliberate human decision -- loosen it by hand in the contract file, not from a single run.",
        step: row,
      });
    }
  }
  return entries;
}

/** A printed patch (agent_replay task's own term for this) -- not a full contract file, since the
 * dashboard never fetches the whole contract text (only the comparison result -- see module docstring).
 * Small enough to read in seconds and apply by hand, exactly this project's own design philosophy for
 * the contract file itself. */
export function buildPatch(scenario: string, accepted: ContractDiffEntry[], acceptedBy: string, runId: string): string {
  const adds = accepted.filter((e) => e.kind === "enter");
  const removes = accepted.filter((e) => e.kind === "leave");
  const lines = [
    `# Patch for agent-replay/contracts/${scenario}.yaml`,
    `# Generated by the agent-replay dashboard's accept flow.`,
    `# Run: ${runId}`,
    `# Accepted by: ${acceptedBy}`,
    `# At: ${new Date().toISOString()}`,
    "#",
    "# Apply by hand: this is a patch, not a replacement file (the dashboard only ever reads the",
    "# comparison result, never the full contract text). For each line below:",
    "#   '+' -> add to the contract's permits: list (adjust the '# k of N runs' count yourself)",
    "#   '-' -> remove the matching line from requires:",
    "",
  ];
  if (!adds.length && !removes.length) lines.push("# (nothing accepted)");
  for (const e of removes) lines.push(`- ${e.line}`);
  for (const e of adds) lines.push(`+ ${e.line}  # 1 of N runs -- this run only so far`);
  lines.push("");
  return lines.join("\n");
}
