import type { ForkModel } from "./model";
import { isTool } from "./model";

/**
 * Phase 2.3 (docs/DECISIONS.md): "Save as scenario" produces a DOWNLOADABLE FILE, never a git write --
 * same constraint, same reasoning, as contract acceptance (engine/contractDiff.ts's buildPatch): the
 * dashboard has no server-side write path into this repo at all, by design (README.md "How an accepted
 * change reaches the repo").
 */

/** Every tool name this run actually passed through live (StepReport.gate_status === "pass_through") --
 * derived from the run's OWN steps rather than invented or hardcoded, so a forked scenario's pass_through
 * list is exactly what THIS run needed, not a guess. */
export function derivedPassThroughTools(model: ForkModel): string[] {
  const tools = new Set<string>();
  for (const s of model.run.result.steps) {
    if (s.gate_status !== "pass_through") continue;
    const call = s.candidate ?? s.golden;
    if (call && isTool(call)) tools.add(call.tool);
  }
  return [...tools];
}

export function buildForkScenarioFile(opts: {
  newName: string;
  model: ForkModel;
  mutation: { tool: string; field: string; value: unknown };
}): string {
  const { newName, model, mutation } = opts;
  const agent = model.run.args.agent_module;
  const passThrough = derivedPassThroughTools(model);
  const prompt = model.run.args.prompt ?? model.run.golden.prompt;
  const lines = [
    "# Paste this entry into agent-replay/scenarios.yaml's \"scenarios:\" list.",
    "# Generated by the agent-replay dashboard's fork feature (Phase 2.3, docs/DECISIONS.md).",
    "#",
    "# A fork is a single live run, not a golden recording -- this scenario cannot be tested yet. Run:",
    `#     agent-replay record ${newName}`,
    "# first, to actually record its own reference run(s); only then does `agent-replay test` work.",
    "",
    `- name: ${newName}`,
    `  agent: ${agent}`,
    `  input: ${JSON.stringify(prompt)}`,
    "  runs: 1",
    ...(passThrough.length ? [`  pass_through: [${passThrough.join(", ")}]`] : []),
    "",
    "# The mutation this scenario was forked with -- scenarios.yaml itself has no mutation field (a",
    "# scenario is just an agent+prompt+runs; --mutate is a gate.py/test-time flag, not something",
    "# recorded here). To make `agent-replay gate` reproduce this exact change against the fresh",
    "# recording above once it exists:",
    `#   agent-replay gate ${newName} --mutate '${mutation.tool}:${JSON.stringify({ [mutation.field]: mutation.value })}'`,
    "",
  ];
  return lines.join("\n");
}

export function downloadForkScenarioFile(newName: string, model: ForkModel, mutation: { tool: string; field: string; value: unknown }): void {
  const text = buildForkScenarioFile({ newName, model, mutation });
  const blob = new Blob([text], { type: "text/yaml" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${newName}.scenario.yaml`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
